from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    initial=True; dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Campus",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120,unique=True)),("code",models.CharField(max_length=30,unique=True))]),
        migrations.CreateModel(name="School",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=180,unique=True)),("code",models.CharField(max_length=30,unique=True))]),
        migrations.CreateModel(name="Department",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=180)),("code",models.CharField(max_length=30)),("school",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="departments",to="repository.school"))]),
        migrations.CreateModel(name="Profile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(choices=[("STUDENT","Student"),("SUPERVISOR","Supervisor"),("LECTURER","Lecturer"),("ADMIN","Administrator")],default="STUDENT",max_length=20)),("phone",models.CharField(blank=True,max_length=30)),("registration_number",models.CharField(blank=True,max_length=80)),("approval_status",models.CharField(choices=[("APPROVED","Approved"),("PENDING","Pending"),("REJECTED","Rejected")],default="APPROVED",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("campus",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="profiles",to="repository.campus")),("department",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="profiles",to="repository.department")),("school",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="profiles",to="repository.school")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="profile",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Project",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=255)),("abstract",models.TextField()),("project_type",models.CharField(choices=[("INDIVIDUAL","Individual"),("GROUP","Group")],default="INDIVIDUAL",max_length=20)),("course",models.CharField(max_length=160)),("academic_year",models.CharField(max_length=20)),("technology",models.CharField(blank=True,max_length=255)),("topic",models.CharField(blank=True,max_length=160)),("keywords",models.CharField(blank=True,max_length=500)),("license",models.CharField(default="CC BY",max_length=100)),("status",models.CharField(choices=[("DRAFT","Draft"),("SUBMITTED","Submitted"),("APPROVED","Approved"),("CHANGES_REQUESTED","Changes requested"),("REJECTED","Rejected"),("PUBLISHED","Published"),("ARCHIVED","Archived")],default="DRAFT",max_length=30)),("review_comment",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("submitted_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("campus",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="projects",to="repository.campus")),("department",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="projects",to="repository.department")),("school",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="projects",to="repository.school")),("student",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="projects",to=settings.AUTH_USER_MODEL)),("supervisor1",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="supervised_projects_1",to=settings.AUTH_USER_MODEL)),("supervisor2",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="supervised_projects_2",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Notification",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=200)),("message",models.TextField()),("notification_type",models.CharField(choices=[("PROJECT_SUBMITTED","Project submitted"),("SUPERVISOR_APPROVAL","Supervisor approval"),("REVIEW_OUTCOME","Review outcome"),("GENERAL","General")],default="GENERAL",max_length=30)),("is_read",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("project",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to="repository.project")),("recipient",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="SupervisorApproval",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("decision",models.CharField(choices=[("PENDING","Pending"),("APPROVED","Approved"),("REJECTED","Rejected")],default="PENDING",max_length=20)),("comment",models.TextField(blank=True)),("decided_at",models.DateTimeField(blank=True,null=True)),("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="supervisor_approvals",to=settings.AUTH_USER_MODEL)),("supervisor",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="supervisor_approval",to="repository.profile"))]),
        migrations.AddConstraint(model_name="department",constraint=models.UniqueConstraint(fields=("school","code"),name="unique_department_code_per_school")),
    ]
